### ISSUE TITLE
Using on scaled-down element

### ISSUE THREAD

**Issue by keithpickering** [fonstok/magnify#1]
I have an element that is scaled down using CSS. I want to use your magnifier plugin to allow the content of said element to be seen at its regular size.

Is this implementation possible with the current code?

**Comment by fonstok** [comment]
Hey, I've been busy so sorry for the delay. Yeah I think so. Just set the data-scale ="1" as an attribute in the opening of the parent tag, or on init 

$(".magnify").jfMagnify({
    center: true,
    **scale:1,**
    containment:'magnify',
    magnifyGlass : '.magnify_glass',
    magnifiedElement: '.magnified_element',
    magnifiedZone:'.magnify_glass',
    elementToMagnify : '.element_to_magnify',
});
